### ISSUE TITLE
Running cypress-split on BitBucket pipeline

### ISSUE THREAD

**Issue by v42a33** [bahmutov/cypress-split#104]
I'm having issues trying to split my tests through BitBucket pipelines. Cypress-split is able to identify all the specs and split them properly using the environment variables SPLIT_INDEX and SPLIT, however **each** parallel step in bb pipelines still tries to run **all** of the tests when the run starts. Can you please help me troubleshoot this? Thank you

Here's what a step will look like: 

cypress-split: there are 30 found specs
cypress-split: split 1 of 10
k  spec                           
-  -------------------------------
1  e2e/client/{testname}_4.cy.ts 
2  e2e/client/{testname}_5.ts      
3  e2e/client/{testname}_6.cy.ts

(Run Starting) 
Running:  {testname}_1.cy.ts                                                           **(1 of 30)**

**Comment by bahmutov** [comment]
https://github.com/bahmutov/cypress-split#install - make sure to return the config object
