### ISSUE TITLE
cypress-split: split 0 of 3

### ISSUE THREAD

**Issue by testingnotebook** [bahmutov/cypress-split#109]
I have a github action like below form following the guides and noticed in the output of the split it says:
Agent 1:  'cypress-split: split 0 of 3'
Agent 2:  'cypress-split: split 1 of 3'
Agent 3:  'cypress-split: split 1 of 3'

Expected split 1 of 3, split 2 of 3, split 3 of 3

`name: Cypress Tests
on: 
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * 0"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}`

**Comment by bahmutov** [comment]
I have not noticed anything suspicious in my https://github.com/bahmutov/cypress-split-example All indices seem correct for all agents. I will change the language for the "split k of N" since it is a little confusing with zero-based indices.

**Comment by bahmutov** [comment]
Is it still not working? Can you turn on debugging logs and see what it says? https://github.com/bahmutov/cypress-split#debugging

**Comment by testingnotebook** [comment]
> Is it still not working? Can you turn on debugging logs and see what it says? https://github.com/bahmutov/cypress-split#debugging

Hi, sorry missed your message.

I can see on v1.15.4 these changes so

cypress-split: there are 3 found specs
cypress-split: chunk 1 of 3
cypress-split: specs from the current directory /home/runner/work/cypress-split-example/cypress-split-example
