### ISSUE TITLE
Question:How can i run if i am using SpecPattern variable in Cypress.config file

### ISSUE THREAD

**Issue by SalmanAhmadQA** [bahmutov/cypress-split#111]
here is the my cypress.config script.

const { defineConfig } = require("cypress");

module.exports = defineConfig({
  projectId: '9iyncm',
  e2e: {
    //baseUrl:"https://app.paismo.com",
    baseUrl:"https://app-stage.paismo.com",
    testIsolation: false,
    viewportWidth: 1660,
    viewportHeight: 1000,
    setupNodeEvents(on, config) {
      config.specPattern = [
        'cypress/e2e/Login.cy.js',
        'cypress/e2e/Employee.cy.js',
        'cypress/e2e/My-Profile-edit/Profile.cy.js',
        'cypress/e2e/My-Profile-edit/Employment.cy.js',
        'cypress/e2e/My-Profile-edit/Payroll-Preferences.cy.js',
        'cypress/e2e/My-Profile-edit/Offboarding.cy.js',
        'cypress/e2e/Full-Employee-edit/Profile.cy.js',
        'cypress/e2e/Full-Employee-edit/Employment.cy.js',
        'cypress/e2e/Full-Employee-edit/Payroll-Preferences.cy.js',
        'cypress/e2e/Full-Employee-edit/Offboarding.cy.js',
        'cypress/e2e/Schedules, Timesheets & Leave/Time-Off-Request.cy.js',
        'cypress/e2e/Settings-/Departments-Work Locations.cy.js',
        'cypress/e2e/Settings-/Work-Scdules-PTO.cy.js',
        'cypress/e2e/Payroll/Run-Payroll.cy.js',

        
      ]
      // IMPORTANT: need to return the changed config
      // so Cypress knows about your changes
      return config
    },

   experimentalRunAllSpecs: true,   // implement node event listeners here
   defaultCommandTimeout: 10000,

  },

   // "experimentalSessionAndOrigin": true,

    
    
    

  
});

**Comment by bahmutov** [comment]
Depends on https://github.com/bahmutov/find-cypress-specs/issues/184 for the list of specs (single filename in the spec pattern works)
