### ISSUE TITLE
Split based on running time

### ISSUE THREAD

**Issue by RobbeCl** [bahmutov/cypress-split#120]
Would it be possible to split the tests not based on name, but based on how long they run? Such that all the parallel machines finish at approximately the same time?

At this point, we have a fairly uneven distribution of tests between our runners.

Thanks!

**Comment by bahmutov** [comment]
Yes, but it would require keep the previous timings. I’m still thinking how to better do it. Sent from my iPhoneOn Oct 12, 2023, at 11:15, Robbe Claessens ***@***.***> wrote:﻿
Would it be possible to split the tests not based on name, but based on how long they run? Such that all the parallel machines finish at approximately the same time?
At this point, we have a fairly uneven distribution of tests between our runners.
Thanks!

**Comment by RobbeCl** [comment]
Do you already have an implementation or are you in planning phase? If there is a way I could help you?

**Comment by bahmutov** [comment]
Just planning Sent from my iPhoneOn Oct 12, 2023, at 11:36, Robbe Claessens ***@***.***> wrote:﻿
Do you already have an implementation or are you in planning phase? If there is a way I could help you?
