### ISSUE TITLE
Include common steps in each chunk

### ISSUE THREAD

**Issue by ngothanhtai** [bahmutov/cypress-split#141]
Hi,

I am using the cypress-cucumber-preprocessor with [common step definitions](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md#example-2-directory-with-common-step-definitions).

I'm facing an issue when using cypress-split, as it seems to split the common step definitions as well. Consequently, I'm getting an error for missing step definitions.

Is there a way to ensure that the common steps are included in every chunk when using cypress-split?

Thank you.

Thanks.

**Comment by bahmutov** [comment]
I am sorry, I don't understand the situation. Can you make a small repo showing the problem?

**Comment by ngothanhtai** [comment]
sorry @bahmutov, I just found out that the problem is with my step definitions configuration.
