### ISSUE TITLE
Question about cypress.config.ts when using plugins/index.js

### ISSUE THREAD

**Issue by gabrielfer** [bahmutov/cypress-split#191]
Hello @bahmutov, first all thank you for this plugin. 

```
export default defineConfig({
  e2e: {
    video: false,
    screenshotOnRunFailure: false,
    fixturesFolder: false,
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config);
    },
  }
});
```

This is my current cypress.config.ts, in this case should I add the cypressSplit() in the index.js file?

**Comment by bahmutov** [comment]
YesSent from my iPhoneOn Dec 20, 2023, at 10:11, Gabriel Fernandes ***@***.***> wrote:﻿
Hello @bahmutov, first all thank you for this plugin.
export default defineConfig({
  e2e: {
    video: false,
    screenshotOnRunFailure: false,
    fixturesFolder: false,
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config);
    },
  }
});

This is my current cypress.config.ts, in this case should I add the cypressSplit() in the index.js file?
