### ISSUE TITLE
Splitting component tests leads to build errors

### ISSUE THREAD

**Issue by alexey-tikhonok** [bahmutov/cypress-split#218]
Hi, thanks for making such a great package.

cypress: 12.7.0
cypress-split: 1.19.0
command in my project: npm run  cy:run

I tried to implement splitting for angular component tests and all my attempts failed, so I created a [repository](https://github.com/alexey-tikhonok/cypress-split-ng-components) with a code based on your examples to provide you with a reproducible example. 

There are some webpack-related errors:

![image](https://github.com/bahmutov/cypress-split/assets/49611302/0e94893f-f3c4-403a-93b5-d678ff4105ed)
![image](https://github.com/bahmutov/cypress-split/assets/49611302/a352b85b-bf25-4837-9e61-16861790c305)

And without splitting there are no errors:

![image](https://github.com/bahmutov/cypress-split/assets/49611302/1554b164-bc26-407e-8a98-e688da6c9060)

**Comment by bahmutov** [comment]
Hmm, it needs the specs to be relative to the project, ughh, I need to think about and experiment with other situations. Right now it returns all absolute filenames
```
cypressSplit(on, config);
// config.specPattern
// has a list of absolute spec filenames 
```
In your case, it seems that it only works if the `config.specPattern` is relative filenames.

**Comment by bahmutov** [comment]
Ok, I think the simplest solution is to transform the specs to relative form, then your project works. I added the code example to the README, see it https://github.com/bahmutov/cypress-split?tab=readme-ov-file#relative-specs-output
