### ISSUE TITLE
question: return config two values

### ISSUE THREAD

**Issue by lucasdonato** [bahmutov/cypress-split#22]
Hello Gleb, I have a question, how do I return 2 values? I need to return the config and the fs.readJSON, I tried to separate the values ​​with a comma but it didn't work.

![image](https://user-images.githubusercontent.com/12953400/218527585-a53181d2-856a-4122-8b10-0c6b350e7566.png)

I tried this way:

**return fs.readJson(path.resolve(`envs/cypress.${file}.json`)), config**

**Comment by HubertArciszewski95** [comment]
Hey @lucasdonato. I think I have a solution for your problem.
It seems that you want to change env dynamically on which your tests will run (dev,test,prod).
Below is my solution for that.

// cypress.config.js
` setupNodeEvents(on, config) {
            setEnvConfig(config);
            return config;
}
`
// setEnvConfig
`
import fs from "fs-extra";
import path from "path";

/**
 * Handles setting config dynamically.
 */
function setEnvConfig(config: Cypress.PluginConfigOptions): void {
    const version = config.env.version || "local";
    const pathToConfigFile = path.resolve("cypress", `config`, `${version}.json`);
    const envConfig = JSON.parse(fs.readFileSync(pathToConfigFile, "utf8"));

    config.baseUrl = envConfig.baseUrl;
    config.env = {
        ...config.env,
        ...envConfig.env,
    };
}

export default setEnvConfig;
`

Under Cypress folder I have created config folder. Where I have config files like:
dev.json
test.json
prod.json

To run tests on specific env I use:  `npm run cy:open -- --env version=dev`
Where my cy:open is a script "cypress open"
