### ISSUE TITLE
Support for component tests

### ISSUE THREAD

**Issue by jamesopti** [bahmutov/cypress-split#24]
Finally got this working in our monorepo only to realize it doesn't work for Cypress component tests.

Is there any reason for that? Would be great to add support for them.

Thanks for making this library!

**Comment by bahmutov** [comment]
Usually the component tests are so fast, they can be executed without splitting, but yeah, I should support running them separately

**Comment by jamesopti** [comment]
Thanks! Yea we use it for a set of "unit" (very large component) tests where interacting with a real dom is crucial. That build of 30 files is approaching 20+ min to run, and we'd like to get it down to under 5min with parallelization.

It'll cost a little more due to shared overhead of installing node_modules for each run but for us it's worth it.
