### ISSUE TITLE
Getting "cypress-split: no specs to run, running an empty spec file /tmp/empty-6-of-6.cy.js" error

### ISSUE THREAD

**Issue by praveenkumar3030** [bahmutov/cypress-split#292]
Hi @bahmutov ,

I have used the Cypress Split plugin in my scripts (I am using the Cucumber Framework and GitLab). 
I am getting the following error when I use the following line of scripts in my GitLab.yml. 
```
  parallel:
    matrix:
      - VG: ['GB', 'US']
        containers: [1, 2, 3, 4, 5]

npx cypress run -e TAGS="@VG",is_ci=true,split=true --browser chrome --spec "cypress/e2e/features/regressionTests/psj/*.feature";
```
In **PSJ** folder there are 5 files inside .

1. feature1
2. feature2
3. feature3
4. feature4
5. feature5

Here, **VG** parameter is nothing but the country value, and we are running 5 features (Spec file) for each and every country. 

It's working fine for the first country, i.e. GB. All the features have been executed on all 5 containers. But for **US** getting the below error on gitlab.
 
`cypress-split: no specs to run, running an empty spec file /tmp/empty-6-of-6.cy.js`

![image](https://github.com/bahmutov/cypress-split-cucumber-example/assets/161488511/cfd20e64-b119-4736-a91d-683424ee8c2b)
![image](https://github.com/bahmutov/cypress-split-cucumber-example/assets/161488511/604d834d-1bd6-4377-900c-56bbad2199d7)

How can I resolve this error when providing example matrix 2*2 or 2*5, 5*3.. containers on the GitLab YML file? Due to the fact that it was unable to locate the Spec file for the upcoming VG param.

I would appreciate it if you could fix this issue. 
Thanks in advance!
Praveenkumar

**Comment by bahmutov** [comment]
Resolved, see lessons in https://cypress.tips/courses/cypress-split
