### ISSUE TITLE
Prevent cypress-split from printing information in the Summary page of GitHub Actions

### ISSUE THREAD

**Issue by igorgiumellizup** [bahmutov/cypress-split#340]
I need it to stop printing information in the GHA Summary page. I tried using this step in the last job:

>       - name: Clear GITHUB_STEP_SUMMARY
>         if: always()
>         run: |
>           echo -n "" > $GITHUB_STEP_SUMMARY

But the split information of each job of the matrix keeps getting printed.

Is there any other solution or workaround for that goal?

**Comment by bahmutov** [comment]
Ok, see https://github.com/bahmutov/cypress-split?tab=readme-ov-file#ci-summary

**Comment by igorgiumellizup** [comment]
Hello, the option to skip the summary just reduces the information, but things are still being printed:
![image](https://github.com/user-attachments/assets/6f1e6a2f-c127-4733-8737-a9c1c17571b5)
Is it possible to reopen this issue?
@bahmutov

**Comment by bahmutov** [comment]
That is not the summary written by this plugin, it is by cypress' own github action, I added a note how to suppress both https://github.com/bahmutov/cypress-split?tab=readme-ov-file#ci-summary
