### ISSUE TITLE
Tests failing when I use split | Github Actions

### ISSUE THREAD

**Issue by filiptunguz** [bahmutov/cypress-split#57]
Hi @bahmutov I'm seeing failed tests when i run cypress tests using cypress split like this:

```
uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
with:
  nComponent: 4
```
      
Tests are running perfectly fine but sometimes some of them fails with this error message:

```
App test
  "before each" hook for "should mount component":
 TypeError: Cannot destructure property 'data' of 'undefined' as it is undefined.
```

     
This is how my App test looks like:

```
import { RouterTestingModule } from '@angular/router/testing';
import { CookieModule } from 'ngx-cookie';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { AppComponent } from './app.component';

describe('App test', () => {
  it('should mount component', () => {
    cy.mount(AppComponent, {
      imports: [
        RouterTestingModule,
        CookieModule.forRoot(),
        MatSnackBarModule,
        HttpClientTestingModule,
      ],
    });
  });
});
```

As you can see it is just basic smoke testing of app component. Sometimes it fails here, sometimes on another component test, sometimes it doesn't fails. 

Do you know why these errors are occurring and can I do something to prevent them?

**Comment by bahmutov** [comment]
Seems like there is a problem with your tests or component, no? Can you provide a full repo with simple test showing the problem?

**Comment by filiptunguz** [comment]
> Seems like there is a problem with your tests or component, no? Can you provide a full repo with simple test showing the problem?

I cannot reproduce the problem because the problem is not related to specific component. 
Your cypress split finds 186 spec files, and sometimes one or two of them fails with that error message, but sometimes it completes with successful message.
Maybe it is because of large number of spec files or something similar to that?
I took some research for error message and it seems like the component is undefined when it tries to mount that component, but component is never undefined.

**Comment by bahmutov** [comment]
I think it will be impossible for me to do anything about it without a reproducible example, I really don't think `cypress-split` has anything to do with mounting the specs, since the plugin only controls the list of specs before they start running.
