### ISSUE TITLE
Using cypress-split locally And using it in combination with Sorry Cypress

### ISSUE THREAD

**Issue by raktim1988** [bahmutov/cypress-split#68]
Hello,

As you might know there is an alternative to cypress cloud, which is Current Or Sorry Cypress which is free. Where we can already run tests in parallel but can we mix Split with the Sorry Cypress? Also I used this in my CLI but it throws me multiple error, is this dependent on each other like the mocks that might have been used first etc. 

npx cypress run --env split=3,splitIndex=0

**Comment by bahmutov** [comment]
I do not care for Current / Sorry so will not comment on that. I am not sure how to answer the second question about problems without any details.
