### ISSUE TITLE
I noticed that one of the container job fails as cypress-split tries to recognise all the tests under cypress/e2e (error message "Can't run because no spec files were found.").  However, I have a custom script that should run the spec files under one folder 'regression-tests' i.e cypress/e2e/regression-tests)

### ISSUE THREAD

**Issue by Indu-aggarwal** [bahmutov/cypress-split#75]
Hi, 

I have the following folder structure in cypress- 
cypress/e2e
1. folder1 is all-tests (has 2 feature files)
2. folder2 is regression-tests (has 4 feature files)

My custom script is to run the tests in one of the folder  "cypress run -s cypress/e2e/regression-tests --env ENV=qa -e TAGS='@regression".

I am using cypress-split plugin for parallelisation using 3 containers however the container 1 job fails with error message "**_Can't run because no spec files were found_**."  I have added the logs from the container job that failed. 

```
> spring-qa-cypress@1.0.0 cy:qa:regression
> cypress run -s cypress/e2e/regression-tests --env ENV=qa -e TAGS='@regression'



DevTools listening on ws://127.0.0.1:46265/devtools/browser/3e19e806-dcac-4264-af7f-15a6b3714a43
[1984:0627/090230.104157:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Couldn't find tsconfig.json. tsconfig-paths will be skipped
cypress-split: there are 6 found specs
cypress-split: split 0 of 3
k  spec                                      
---------------------------------------------
1  cypress/e2e/all-tests/duckduckgo.feature  
2  cypress/e2e/all-tests/other-search.feature

Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /home/runner/work/spring-qa-cypress/spring-qa-cypress/cypress/e2e/regression-tests
Error: The process '/usr/local/bin/npm' failed with exit code 1
```

My question is why the container 1 job tries to find the specs files in the folder that is not part of the custom script? Any help is appreciated. Thank you :)

**Comment by t-l-k** [comment]
@bahmutov similar issues encountered, is `cypress-split` compatible with explicit `e2e.specPattern` settings, e.g. an array of `.feature` specs?

**Comment by Indu-aggarwal** [comment]
Hi, 

I have set up the project publically which illustrates the issue that I was referring to.  This time I also removed the env variable and just have the --spec variable defined in the custom script. 

The project can be found here 
`https://github.com/Indu-aggarwal/qa-cypress`

> https://github.com/Indu-aggarwal/qa-cypress

```
> cypress run --spec cypress/e2e/features


DevTools listening on ws://127.0.0.1:4[52](https://github.com/Indu-aggarwal/qa-cypress/actions/runs/5500883410/jobs/10024108263#step:3:53)91/devtools/browser/7b90d[53](https://github.com/Indu-aggarwal/qa-cypress/actions/runs/5500883410/jobs/10024108263#step:3:54)a-3b2d-4c1b-ba88-f461fe2316d8
[2000:0709/163730.713725:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Couldn't find tsconfig.json. tsconfig-paths will be skipped
cypress-split: there are 6 found specs
cypress-split: split 0 of 3
k  spec                                       
-  -------------------------------------------
1  cypress/e2e/advance-features/todo.feature  
2  cypress/e2e/advance-features/window.feature

Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /home/runner/work/qa-cypress/qa-cypress/cypress/e2e/features
Error: The process '/usr/local/bin/npm' failed with exit code 1
```

**Comment by bahmutov** [comment]
This is due to https://github.com/bahmutov/cypress-split#list-of-specs which has a workaround (or Cypress test runner can implement the necessary change for this plugin to work automatically)
