### ISSUE TITLE
spec="spec1,spec2,spec3" under --env option fails with "Cannot parse as valid JSON" error

### ISSUE THREAD

**Issue by serhiikovalenkoextcheckrcom** [bahmutov/cypress-split#79]
Hi!

`npx cypress run --env split=true,spec="spec1,spec2,spec3"` or `npx cypress run --env spec="spec1,spec2,spec3"` fails:
<img width="1101" alt="image" src="https://github.com/bahmutov/cypress-split/assets/112432131/a55bd132-ef9d-4a71-a865-eed46ef95305">

The same about` npx cypress run --env split=2,splitIndex=0,spec="spec1,spec2,spec3"`

It works fine with 1 spec, and I didn't succeed to find a syntax which allows to pass more than one spec.
I've seen there are examples like `cypress run --env flags='{"feature-a":true,"feature-b":false}'` in documentation, but didn't found examples like mine.

I'm wondering if there is a way to use it as described in ReadMe?

Thank you!

**Comment by bahmutov** [comment]
Before I update the README, can you try passing specs using an environment variable, something like this:
```
$ SPEC="..." npx cypress run --browser chrome --env split=true
```

**Comment by serhiikovalenkoextcheckrcom** [comment]
SPEC="..." npx cypress run --browser chrome --env split=true - this working, thank you!
