### ISSUE TITLE
Question:How can i run parallel tests in aws code build using this plugin?

### ISSUE THREAD

**Issue by bhaumikbhut** [bahmutov/cypress-split#93]
I am not sure how can i use this plugin for aws code build setup?

is there any example available how can i run parallel tests using this plugin in aws code build?

**Comment by tommy-anderson** [comment]
I'm not a user of AWS CodeBuild, but I see they have the [build-matrix](https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build.html#batch_build_matrix) option, which allows you to spawn multiple parallel containers similar to GitHub Actions.
You could then map each container matrix value to a SPLIT_INDEX

**Comment by bahmutov** [comment]
I added a lesson to my https://cypress.tips/courses/cypress-split course. Since it took a while to figure out how to run AWS CodeBuild correctly, I have decided to put this lesson under paid content.
